backend:
  name: git-gateway
  repo: pvul/nextjs-netlify-cms-content
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    fields:
      - label: 'Hero Title'
        name: 'hero_title'
        widget: 'string'
      - label: 'Hero Description'
        name: 'hero_description'
        widget: 'markdown'
      - label: 'Hero Image'
        name: 'hero_image'
        widget: 'image'
